# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/My Drive/UIUC/Year 2 S/ECE 385/Vivado/Lab6.1/Lab6.1.srcs/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0.xci
# IP: The module: 'mb_block_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/My Drive/UIUC/Year 2 S/ECE 385/Vivado/Lab6.1/Lab6.1.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: h:/My Drive/UIUC/Year 2 S/ECE 385/Vivado/Lab6.1/Lab6.1.srcs/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0.xci
# IP: The module: 'mb_block_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/My Drive/UIUC/Year 2 S/ECE 385/Vivado/Lab6.1/Lab6.1.gen/sources_1/bd/mb_block/ip/mb_block_ilmb_v10_0/mb_block_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
